### ISSUE TITLE
Depósito em conta corrente

### ISSUE THREAD

**Issue by guimpo** [guimpo/internet_banking#7]
ID: 1.1
Grupo: Conta

**Comment by AmandaSao** [comment]
1 - Falta validar se é número(se coloca type = "number", a resposta para coisas que não são número já vai ser solicitação incorreta(http400))
2 - Não deixar ser negativo("min" não está implementado em angular 2 pelo que encontrei, se quiser fazer vai ter que ser no back, ou implementando no front).
